version: '3.8'
services:
    php:
        image: php:8.2-fpm
        volumes:
            - ./src:/var/www/html
        ports:
            - "9000:9000"
        restart: unless-stopped

    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_app
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - laravel

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - laravel
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
