# fly.toml app configuration file generated for macademy on 2024-03-29T21:49:54+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'macademy'
primary_region = 'ams'

APP_KEY='36b76a269df40928'

[build]

[http_service]
    internal_port = 9000
    force_https = true
    auto_stop_machines = true
    auto_start_machines = true
    min_machines_running = 0
    [http_service.concurrency]
        type = "requests"
        soft_limit = 200
        hard_limit = 250

[http_service.tls_options]
    alpn = ["h2", "http/1.1"]
    versions = ["TLSv1.2", "TLSv1.3"]
    default_self_signed = false


[[vm]]
    size = 'performance-8x'


# docker-compose up -d --build
# docker-compose ps

# docker-compose exec app bash
# composer install
# php artisan key:generate
